language: android
jdk: oraclejdk8
# See https://github.com/travis-ci/travis-ci/issues/5582
sudo: required
env:
  - BUILD_TOOLS_VERSION=27.0.0
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 300 # 5 minutes
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
install: nvm install 7
before_script:
  - chmod +x gradlew building/setup.sh building/build.sh building/upload.sh
  - building/setup.sh
script: ./gradlew clean assembleDebug check
# TODO add back once all NDA protected libraries have graduated to public alpha/beta
#script: building/build.sh
#after_success: building/upload.sh
after_failure:
  - cat app/build/reports/lint-results.xml
  - cat app/build/reports/lint-results.html
  - cat app/build/reports/checkstyle/checkstyle.html
  - cat app/build/reports/findbugs.html
  - cat app/build/reports/pmd.html
