language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
android:
  components:
    - android-25
    - tools
    - platform-tools
    - build-tools-25.0.0
    - extra-android-m2repository
    - extra-google-m2repository
before_script:
  - mv travis-dummies/google-services.json app/google-services.json
  - mv travis-dummies/keystore.properties keystore.properties
  - mv travis-dummies/keystore.jks app/keystore.jks

  - openssl aes-256-cbc -K $encrypted_2efb677b0ec0_key -iv $encrypted_2efb677b0ec0_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar
  - mv keystore.jks app/keystore.jks
  - mv google-services.json app/google-services.json
  - mv google-play-auto-publisher.json app/google-play-auto-publisher.json

  - chmod +x gradlew
script: ./gradlew clean build publishApkRelease
after_failure:
  - cat app/build/outputs/lint-results-debug.xml
  - cat app/lint-report.html
after_success:
  - mv app/build/output/apk/app-release.apk app-release.apk
  - mv app/build/outputs/mapping/release/mapping.txt mapping.txt

  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-133.0.0-linux-x86_64.tar.gz
  - tar xf google-cloud-sdk-133.0.0-linux-x86_64.tar.gz
  - echo "y" | ./google-cloud-sdk/bin/gcloud components update alpha
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file app/google-play-auto-publisher.json

  - git init
  - git remote add mapping $git_mapping_login
  - git add mapping.txt app-release.apk
  - git commit -a -m "Added new apk + mapping"
  - git push -u mapping master &> /dev/null

  - ./google-cloud-sdk/bin/gcloud alpha test android run --async --app app-release.apk --device-ids m0,Nexus6P --os-version-ids 18,25 --orientations portrait --project robot-scouter-app
